# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = "$directory$java$python$lua$git_branch"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](bold red) "

[directory]
# style = "fg:#5f94da bold"

[python]
symbol = "[ ](yellow)"

[shell]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
