#!/bin/python3

import subprocess
import sys

process = subprocess.run(["xbacklight","-get"], capture_output=True)
percent = str(process.stdout)[2:-3]

arg = sys.argv[1]

if arg == "+":
    subprocess.run(["xbacklight",str(int(percent)+10)], capture_output=True)
elif arg == "-" and int(percent)>10:
    subprocess.run(["xbacklight",str(int(percent)-10)], capture_output=True)

